#
# docker-compose.yml
#
# Docker compose file for Postgres to support TruckApp
#
# Key Considerations:
# - Postgres service is on a single external bridge network
#
# Author: Ogonna Anaekwe
#

version: '3'

#
# Services
#
services:

    #
    # Postgres database
    #
    postgresdb:
      image: postgres:latest
      volumes:
        - ./db/postgres:/docker-entrypoint-initdb.d
      environment:
        POSTGRES_PASSWORD: my-secret-pw
        POSTGRES_DB: trucks
      ports:
        - "5432:5432"

#
# Networks
#
networks:
    localnet:
        # driver: bridge
        external: true